// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gapuktvldpbbsuscgbbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcHVrdHZsZHBiYnN1c2NnYmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MzcyNjQsImV4cCI6MjA4NTMxMzI2NH0.u_km0ap7DOuX_MHXIEtDI_oIFR242VnNZc5qmfIG0x0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});